name: Docker Build and Push

####################################################################################################
## This works now ================================================================================ #
####################################################################################################

# Run this Build for all pushes to 'main' branch, or tagged releases.
on:
  push:
    paths:
      - App/**
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

permissions:
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v3.3.0


      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        # Only login if not a PR, as PRs only trigger a Docker build and not a push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      ###############################################
      # Build/Push the 'demarauder/zombrary' image
      ###############################################
      - name: Build, tag, and push image to Docker hub
        id: build-image
        run: |
          cd App
          docker image build \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/zombrary:latest \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/zombrary:${{ env.SHORT_SHA }} \
          .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zombrary:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zombrary:${{ env.SHORT_SHA }}   
        